import pygame
pygame.init()
display_info = pygame.display.Info()

WIDTH = display_info.current_w * 0.7
HEIGHT = display_info.current_h * 0.7
PLAYING_TIME = 60
TEXT_COORDINATES = (50, 200)
BACKGROUND_IMAGE_PATH = 'Image/background.png'
PLAYING_BACKGROUND_PATH = 'Image/playing_background.jpg'
RESULTS_FILE_PATH = 'txt/results'
RECORD_FILE_PATH = 'txt/record'
LINE_HEIGHT = 50
TYPED_TEXT_COORDINATES = (50, 250)
TIMER_POSITION = (50, 50)
SCORE_POSITION = (WIDTH * 0.9, 100)
SCORE_PERCENT_POSITION= (WIDTH * 0.9, 150)
MISTAKES_POSITION = (WIDTH * 0.9, 50)
BORDER_WIDTH = 4

START_BUTTON_POSITION_WIDTH = WIDTH * 11 / 40
START_BUTTON_POSITION_HEIGHT = HEIGHT / 4
START_BUTTON_SIZE_WIDTH = WIDTH * 18 / 40
START_BUTTON_SIZE_HEIGHT = 120
START_BUTTON_TEXT_POSITION = (WIDTH / 2, HEIGHT / 4 + 60)
START_BUTTON_TEXT_SIZE = 120

SCORES_BUTTON_POSITION_WIDTH = WIDTH / 3
SCORES_BUTTON_POSITION_HEIGHT = HEIGHT * 23 / 40
SCORES_BUTTON_SIZE_WIDTH = WIDTH / 3
SCORES_BUTTON_SIZE_HEIGHT = 70
SCORES_BUTTON_TEXT_POSITION = (WIDTH / 2, HEIGHT * 13 / 21)
SCORES_BUTTON_TEXT_SIZE = 70

RESET_BUTTON_POSITION_WIDTH = WIDTH / 14 
RESET_BUTTON_POSITION_HEIGHT = HEIGHT / 14
RESET_BUTTON_SIZE_WIDTH = WIDTH / 3
RESET_BUTTON_SIZE_HEIGHT = 40
RESET_BUTTON_TEXT_POSITION = (WIDTH * 29 / 120, HEIGHT / 14 + 20)
RESET_BUTTON_TEXT_SIZE = 40

START_BUTTON_X_START = WIDTH * 11 / 40
START_BUTTON_X_END = WIDTH * 29 / 40
START_BUTTON_Y_START = HEIGHT / 4
START_BUTTON_Y_END = HEIGHT / 4 + 120

SCORES_BUTTON_X_START = WIDTH / 3
SCORES_BUTTON_X_END = WIDTH * 2 / 3
SCORES_BUTTON_Y_START = HEIGHT * 23 / 40
SCORES_BUTTON_Y_END = HEIGHT * 23 / 40 + 70

SCORE_HEIGHT_FACTOR = 14 / 20
MISTAKES_HEIGHT_FACTOR = 16 / 20
POINTS_HEIGHT_FACTOR = 12 / 20
PERCENT_HEIGHT_FACTOR = 18/20

SCORE_HEIGHT_FACTOR_ALT = 3 / 5
MISTAKES_HEIGHT_FACTOR_ALT = 4 / 5
POINTS_HEIGHT_FACTOR_ALT = 0.5

FONT_SIZE_NEW_RECORD = 100
FONT_SIZE_POINTS = 100
FONT_SIZE_RES = 70

NEW_RECORD_TEXT_POSITION = (WIDTH / 2, HEIGHT / 3)

RESET_BUTTON_LEFT = WIDTH / 14
RESET_BUTTON_RIGHT = WIDTH * (1 / 14 + 1 / 3)
RESET_BUTTON_TOP = HEIGHT / 14
RESET_BUTTON_BOTTOM = HEIGHT / 14 + 40
ESC_BUTTON_POSITION = (WIDTH * 0.8, HEIGHT / 10)
DATA_TIME_SCORE_POSITION_WIDTH = WIDTH / 10
ESC_TEXT_SIZE = 30
RESULT_TEXT_SIZE = 56
RESULT_BUTTON_POSITION_WIDTH = WIDTH / 10
RESULT_HEIGHT = HEIGHT / 5